# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/russell/leds/thematrix/panel_test/panel_test.cache/wt [current_project]
set_property parent.project_path /home/russell/leds/thematrix/panel_test/panel_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
add_files -quiet /home/russell/leds/thematrix/panel_test/panel_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/russell/leds/thematrix/panel_test/panel_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  /home/russell/leds/thematrix/panel_test/panel_test.srcs/sources_1/imports/rtl/matrix.v
  /home/russell/leds/thematrix/panel_test/panel_test.srcs/sources_1/imports/rtl/beagle01.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top beagle01 -part xc7z010clg400-1


write_checkpoint -force -noxdef beagle01.dcp

catch { report_utilization -file beagle01_utilization_synth.rpt -pb beagle01_utilization_synth.pb }
