# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/russell/leds/thematrix/panel_test/panel_test.srcs/sources_1/ip/bram_bottom/bram_bottom.xci
# IP: The module: 'bram_bottom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/russell/leds/thematrix/panel_test/panel_test.srcs/sources_1/ip/bram_bottom/bram_bottom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_bottom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/russell/leds/thematrix/panel_test/panel_test.srcs/sources_1/ip/bram_bottom/bram_bottom.xci
# IP: The module: 'bram_bottom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/russell/leds/thematrix/panel_test/panel_test.srcs/sources_1/ip/bram_bottom/bram_bottom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_bottom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
